
baseURL = "https://sri-shubham.github.io"

# The name of this wonderful theme ;-).
theme = 'hugo-PaperMod'

# Basic metadata configuration for your blog.
title = "Shubham Srivastava"
author = "Shubham Srivastava"
copyright = "Copyright Â© 2024, Shubham Srivastava."
languageCode = "en-US"
paginate     = 10

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
  tags = "/:slug"

[params]
  # The "description" of your website. This is used in the meta data of your generated html.
  description = "Hello World! ğŸ‘‹ I'm Shubham, a passionate coder who loves building tech wonders. With a knack for Golang and a flair for microservices, I'm on a journey to reshape the digital landscape."

  # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
  # Hint: It's good practise to also put a "favicon.ico"-file into your "static"-folder.
  favicon = "favicon.ico"

  # These "images" are used for the structured data templates. This will show up, when
  # services like Twitter or Slack want to generate a preview of a link to your site.
  # See https://gohugo.io/templates/internal#twitter-cards and
  # https://gohugo.io/templates/internal#open-graph.
  images = ["images/home.png"]

  # Another "title" :-). This one is used as the site_name on the Hugo's internal
  # opengraph structured data template.
  title = "Shubham Srivastava"

  hideFooter=true

  disableSpecial1stPost=true

[params.homeInfoParams]
  Title = "Hello, World! âœ¨"
  Content = "Step into the enchanting realm where code dances with creativity! ğŸ‘¨â€ğŸ’»âœ¨ I'm Shubham, your tech maestro on this digital odyssey. Explore the wonders of Golang, unravel the magic of microservices, and immerse yourself in all things geeky. Together, let's transform aspirations into digital masterpieces â€“ are you prepared for a tech-tastic journey? ğŸŒğŸš€"

[[params.socialIcons]]
  name = "Github"
  url = "https://github.com/sri-shubham"

[[params.socialIcons]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/sri-shubham"

[[menu.main]]
identifier = "Blog"
name = "blog"
url = "/blog/"
weight = 10

[[menu.main]]
identifier = "Projects"
name = "projects"
url = "/projects/"
weight = 20

[[menu.main]]
identifier = "About"
name = "about"
url = "/about/"
weight = 30

[[menu.main]]
identifier = "CV"
name = "cv"
url = "/cv/"
weight = 40


[markup.goldmark.renderer]
  unsafe = true
